"""empty message

Revision ID: 3857efa43be1
Revises: b701ef0c1483
Create Date: 2023-09-21 17:39:59.837089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3857efa43be1'
down_revision = 'b701ef0c1483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cars_car_id_key', 'cars', type_='unique')
    op.drop_column('cars', 'car_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('car_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('cars_car_id_key', 'cars', ['car_id'])
    # ### end Alembic commands ###
